### ISSUE TITLE
Missing AndroidRelease & KmiGeneration strings 

### ISSUE THREAD

**Issue by hopez13** [tiann/KernelSU#861]
Latest Kernel Build: [android12-5.10.177_2023-06-boot-gz.img.gz](https://github.com/tiann/KernelSU/releases/download/v0.6.6/android12-5.10.177_2023-06-boot-gz.img.gz) 
is missing AndroidRelease & KmiGeneration Info

**Screenshots**

![IMG_20230812_112907](https://github.com/tiann/KernelSU/assets/140780838/a4bae28f-0bdb-478d-9281-efbed5026269)

**Expected Output**
`5.10.177-AndroidRelease-KmiGeneration-suffix`

**Comment by tiann** [comment]
This has been fixed, please check the latest ci.

**Comment by chenxiaolong** [comment]
By the way, if disk space is still an issue and `.repo` too big, this (hacky) approach seems to work in my local testing. It computes and saves the version string to `.scmversion` before `.repo` is deleted. Further runs of `setlocalversion` will query the existing `.scmversion` file.

```diff
diff --git a/build.sh b/build.sh
index f67cbc8..86ce593 100755
--- a/build.sh
+++ b/build.sh
@@ -635,6 +635,11 @@ if [ "${SKIP_MRPROPER}" != "1" ] ; then
   set +x
 fi
 
+# Save .scmversion before deleting the git directory to preserve KMI version in
+# the Linux version string
+(cd "${OUT_DIR}" && "${ROOT_DIR}/${KERNEL_DIR}"/scripts/setlocalversion --save-scmversion "${ROOT_DIR}/${KERNEL_DIR}" "${BRANCH}" "${KMI_GENERATION}")
+rm -rf "${ROOT_DIR}/.repo"
+
 if [ -n "${PRE_DEFCONFIG_CMDS}" ]; then
   echo "========================================================"
   echo " Running pre-defconfig command(s):"
```
